// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wed.Models.EF;

#nullable disable

namespace wed.Migrations
{
    [DbContext(typeof(FoodContext))]
    [Migration("20260726090339_s2")]
    partial class s2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Database.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("Core.Database.Models.Authorized", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoleId");

                    b.ToTable("Authorized");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ce01ca4-68e2-48df-96b5-0997002b51fb"),
                            GroupId = new Guid("164eadac-199a-4db7-bbc3-81b6254767b9"),
                            RoleId = new Guid("76d93c1d-3457-4624-8d6a-8a8d3b780458")
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f053ba68-398a-4019-87a1-5bc9466e9fe4"),
                            CreatedBy = new Guid("11336570-9607-4634-8244-207e19971e98"),
                            CreatedOn = new DateTime(2026, 7, 26, 16, 3, 38, 388, DateTimeKind.Local).AddTicks(8539),
                            Name = "Root"
                        },
                        new
                        {
                            Id = new Guid("647dced7-e87d-4ec8-9702-2c5281e77911"),
                            CreatedBy = new Guid("11336570-9607-4634-8244-207e19971e98"),
                            CreatedOn = new DateTime(2026, 7, 26, 16, 3, 38, 388, DateTimeKind.Local).AddTicks(8722),
                            Name = "Authorized",
                            ParentId = new Guid("f053ba68-398a-4019-87a1-5bc9466e9fe4")
                        },
                        new
                        {
                            Id = new Guid("3bcd9c68-1b73-44c9-aba7-d167b98cfe54"),
                            CreatedBy = new Guid("11336570-9607-4634-8244-207e19971e98"),
                            CreatedOn = new DateTime(2026, 7, 26, 16, 3, 38, 388, DateTimeKind.Local).AddTicks(8874),
                            Name = "Nhóm quyền",
                            ParentId = new Guid("647dced7-e87d-4ec8-9702-2c5281e77911")
                        },
                        new
                        {
                            Id = new Guid("f46aa2d3-f286-41a1-86da-592f0f17e2fc"),
                            CreatedBy = new Guid("11336570-9607-4634-8244-207e19971e98"),
                            CreatedOn = new DateTime(2026, 7, 26, 16, 3, 38, 388, DateTimeKind.Local).AddTicks(8878),
                            Name = "Article",
                            ParentId = new Guid("f053ba68-398a-4019-87a1-5bc9466e9fe4")
                        },
                        new
                        {
                            Id = new Guid("18015973-694b-4959-9e6f-0f4e24e3985b"),
                            CreatedBy = new Guid("11336570-9607-4634-8244-207e19971e98"),
                            CreatedOn = new DateTime(2026, 7, 26, 16, 3, 38, 388, DateTimeKind.Local).AddTicks(8881),
                            Name = "Product",
                            ParentId = new Guid("f053ba68-398a-4019-87a1-5bc9466e9fe4")
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            Id = new Guid("164eadac-199a-4db7-bbc3-81b6254767b9"),
                            Name = "Quản trị viên"
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11336570-9607-4634-8244-207e19971e98"),
                            CreatedOn = new DateTime(2026, 7, 26, 16, 3, 38, 387, DateTimeKind.Local).AddTicks(5391),
                            Email = "khangtc.23th@sv.dla.edu.vn",
                            GroupId = new Guid("164eadac-199a-4db7-bbc3-81b6254767b9"),
                            LoginName = "khang",
                            Name = "Tống Chí Khang",
                            Password = "c4ca4238a0b923820dcc509a6f75849b",
                            Picture = "/img/users/TongKhang.jpg"
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Intro")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Core.Database.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76d93c1d-3457-4624-8d6a-8a8d3b780458"),
                            CategoryId = new Guid("3bcd9c68-1b73-44c9-aba7-d167b98cfe54"),
                            Code = "view-group",
                            Name = "Xem danh sách"
                        },
                        new
                        {
                            Id = new Guid("ab095bc1-31af-4b00-9fc5-e4e6f0f1121c"),
                            CategoryId = new Guid("3bcd9c68-1b73-44c9-aba7-d167b98cfe54"),
                            Code = "edit-group",
                            Name = "Cập nhật"
                        },
                        new
                        {
                            Id = new Guid("dbb49494-3cca-4357-89c1-e954ddc2d4b3"),
                            CategoryId = new Guid("3bcd9c68-1b73-44c9-aba7-d167b98cfe54"),
                            Code = "save-group",
                            Name = "Lưu"
                        },
                        new
                        {
                            Id = new Guid("442979c9-9c96-42af-afde-0be7c02135e7"),
                            CategoryId = new Guid("3bcd9c68-1b73-44c9-aba7-d167b98cfe54"),
                            Code = "delete-group",
                            Name = "Xóa"
                        });
                });

            modelBuilder.Entity("Core.Database.Models.Authorized", b =>
                {
                    b.HasOne("Core.Database.Models.Group", "Group")
                        .WithMany("Authorizeds")
                        .HasForeignKey("GroupId");

                    b.HasOne("Core.Database.Models.Role", "Role")
                        .WithMany("Authorizeds")
                        .HasForeignKey("RoleId");

                    b.Navigation("Group");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Core.Database.Models.Category", b =>
                {
                    b.HasOne("Core.Database.Models.Category", "Parent")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Core.Database.Models.Member", b =>
                {
                    b.HasOne("Core.Database.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Database.Models.Product", b =>
                {
                    b.HasOne("Core.Database.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Database.Models.Role", b =>
                {
                    b.HasOne("Core.Database.Models.Category", "Category")
                        .WithMany("Roles")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Database.Models.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Products");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Core.Database.Models.Group", b =>
                {
                    b.Navigation("Authorizeds");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Core.Database.Models.Role", b =>
                {
                    b.Navigation("Authorizeds");
                });
#pragma warning restore 612, 618
        }
    }
}
